apiVersion: v1
kind: ConfigMap
metadata:
  name: cliente-config
  labels:
    app.kubernetes.io/name: cliente
    app.kubernetes.io/part-of: oficina-mecanica
data:
  SERVER_PORT: "8081"
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-mecanica:5432/mecanica_cliente
