apiVersion: v1
kind: ConfigMap
metadata:
  name: estoque-config
  labels:
    app.kubernetes.io/name: estoque
    app.kubernetes.io/part-of: oficina-mecanica
data:
  SERVER_PORT: "8085"
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-mecanica:5432/mecanica_estoque
