apiVersion: v1
kind: ConfigMap
metadata:
  name: servico-config
  labels:
    app.kubernetes.io/name: servico
    app.kubernetes.io/part-of: oficina-mecanica
data:
  SERVER_PORT: "8084"
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-mecanica:5432/mecanica_servico
