apiVersion: v1
kind: ConfigMap
metadata:
  name: veiculo-config
  labels:
    app.kubernetes.io/name: veiculo
    app.kubernetes.io/part-of: oficina-mecanica
data:
  SERVER_PORT: "8082"
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-mecanica:5432/mecanica_veiculo
