apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mecanica

resources:
  - ../../base
  - database/init-databases-configmap.yaml
  - database/postgresql-service.yaml
  - database/postgresql-statefulset.yaml

secretGenerator:
  - name: mecanica-shared-secrets
    envs:
      - secrets/shared.env
  - name: atendimento-secrets
    envs:
      - secrets/atendimento.env
  - name: external-services-secrets
    envs:
      - secrets/external-services.env

images:
  - name: mecanica/cliente
    newTag: local
  - name: mecanica/veiculo
    newTag: local
  - name: mecanica/funcionario
    newTag: local
  - name: mecanica/servico
    newTag: local
  - name: mecanica/estoque
    newTag: local
  - name: mecanica/atendimento
    newTag: local
