services:
  postgres-atendimento:
    image: 'postgres:latest'
    container_name: postgres-atendimento
    environment:
      - 'POSTGRES_DB=mecanica_atendimento'
      - 'POSTGRES_USER=mecanica'
      - 'POSTGRES_PASSWORD=mecanica'
    ports:
      - '5437:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mecanica -d mecanica_atendimento"]
      interval: 10s
      timeout: 5s
      retries: 5
