spring:
  application:
    name: funcionario-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/mecanica_funcionario}
    username: ${SPRING_DATASOURCE_USERNAME:mecanica}
    password: ${SPRING_DATASOURCE_PASSWORD:mecanica}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  lifecycle:
    timeout-per-shutdown-phase: 30s

server:
  port: 8083
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

security:
  jwt:
    secret: ${JWT_SECRET:0123456789abcdef0123456789abcdef}
