services:
  postgres-funcionario:
    image: 'postgres:latest'
    container_name: postgres-funcionario
    environment:
      - 'POSTGRES_DB=mecanica_funcionario'
      - 'POSTGRES_USER=mecanica'
      - 'POSTGRES_PASSWORD=mecanica'
    ports:
      - '5434:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mecanica -d mecanica_funcionario"]
      interval: 10s
      timeout: 5s
      retries: 5
