apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mecanica-production

resources:
  - ../../base
  - database/postgresql-external-service.yaml

patches:
  - path: patches/atendimento-config.yaml
  - path: patches/common-config.yaml
  - target:
      version: v1
      kind: Namespace
      name: mecanica
    patch: |-
      - op: replace
        path: /metadata/name
        value: mecanica-production
  - target:
      group: autoscaling
      version: v2
      kind: HorizontalPodAutoscaler
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 2
  - target:
      group: apps
      version: v1
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always

images:
  - name: mecanica/cliente
    newName: ghcr.io/fiap-mechanics/mecanica-cliente
    newTag: latest
  - name: mecanica/veiculo
    newName: ghcr.io/fiap-mechanics/mecanica-veiculo
    newTag: latest
  - name: mecanica/funcionario
    newName: ghcr.io/fiap-mechanics/mecanica-funcionario
    newTag: latest
  - name: mecanica/servico
    newName: ghcr.io/fiap-mechanics/mecanica-servico
    newTag: latest
  - name: mecanica/estoque
    newName: ghcr.io/fiap-mechanics/mecanica-estoque
    newTag: latest
  - name: mecanica/atendimento
    newName: ghcr.io/fiap-mechanics/mecanica-atendimento
    newTag: latest
