apiVersion: v1
kind: Service
metadata:
  name: postgres-mecanica
  labels:
    app.kubernetes.io/name: postgres-mecanica
    app.kubernetes.io/part-of: oficina-mecanica
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: postgres-mecanica
  ports:
  - name: postgresql
    port: 5432
    targetPort: postgresql
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-mecanica-headless
  labels:
    app.kubernetes.io/name: postgres-mecanica
    app.kubernetes.io/part-of: oficina-mecanica
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: postgres-mecanica
  ports:
  - name: postgresql
    port: 5432
    targetPort: postgresql
    protocol: TCP
