apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mecanica

resources:
  - namespace.yaml
  - configmaps/common.yaml
  - configmaps/cliente.yaml
  - configmaps/veiculo.yaml
  - configmaps/funcionario.yaml
  - configmaps/servico.yaml
  - configmaps/estoque.yaml
  - configmaps/atendimento.yaml
  - deployments/cliente.yaml
  - deployments/veiculo.yaml
  - deployments/funcionario.yaml
  - deployments/servico.yaml
  - deployments/estoque.yaml
  - deployments/atendimento.yaml
  - services/cliente.yaml
  - services/veiculo.yaml
  - services/funcionario.yaml
  - services/servico.yaml
  - services/estoque.yaml
  - services/atendimento.yaml
  - hpa/cliente.yaml
  - hpa/veiculo.yaml
  - hpa/funcionario.yaml
  - hpa/servico.yaml
  - hpa/estoque.yaml
  - hpa/atendimento.yaml
